#!/bin/bash

set -e

ocamlbuild tools/libgen.byte
echo Ext.Error
./libgen.byte tools/jsduck/Ext.Error.json 
echo Ext.Class
./libgen.byte tools/jsduck/Ext.Class.json
echo Ext.Base
./libgen.byte tools/jsduck/Ext.Base.json
echo Ext.util.ElementContainer
./libgen.byte tools/jsduck/Ext.util.ElementContainer.json
echo Ext.util.KeyMap
./libgen.byte tools/jsduck/Ext.util.KeyMap.json
echo Ext.util.Observable
./libgen.byte tools/jsduck/Ext.util.Observable.json
echo Ext.util.Offset
./libgen.byte tools/jsduck/Ext.util.Offset.json
echo Ext.util.Region
./libgen.byte tools/jsduck/Ext.util.Region.json
echo Ext.util.Point
./libgen.byte tools/jsduck/Ext.util.Point.json
echo Ext.dd.DragDrop
./libgen.byte tools/jsduck/Ext.dd.DragDrop.json
echo Ext.dd.DD
./libgen.byte tools/jsduck/Ext.dd.DD.json
echo Ext.dd.DDProxy
./libgen.byte tools/jsduck/Ext.dd.DDProxy.json
echo Ext.dd.DDTarget
./libgen.byte tools/jsduck/Ext.dd.DDTarget.json
echo Ext.dd.StatusProxy
./libgen.byte tools/jsduck/Ext.dd.StatusProxy.json
echo Ext.dd.DragSource
./libgen.byte tools/jsduck/Ext.dd.DragSource.json
echo Ext.dd.DragTracker
./libgen.byte tools/jsduck/Ext.dd.DragTracker.json
echo Ext.EventObject
./libgen.byte tools/jsduck/Ext.EventObject.json
echo Ext.dom.AbstractElement
./libgen.byte tools/jsduck/Ext.dom.AbstractElement.json 
echo Ext.dom.AbstractElement.Fly
./libgen.byte tools/jsduck/Ext.dom.AbstractElement.Fly.json 
echo Ext.ElementLoader
./libgen.byte tools/jsduck/Ext.ElementLoader.json 
echo Ext.dom.Element
./libgen.byte tools/jsduck/Ext.dom.Element.json 
echo Ext.util.Renderable
./libgen.byte tools/jsduck/Ext.util.Renderable.json 
echo Ext.state.Stateful
./libgen.byte tools/jsduck/Ext.state.Stateful.json
echo Ext.util.Animate
./libgen.byte tools/jsduck/Ext.util.Animate.json 
echo Ext.ComponentLoader
./libgen.byte tools/jsduck/Ext.ComponentLoader.json 
echo Ext.AbstractPlugin
./libgen.byte tools/jsduck/Ext.AbstractPlugin.json 
echo Ext.AbstractComponent
./libgen.byte tools/jsduck/Ext.AbstractComponent.json 
echo Ext.util.Floating
./libgen.byte tools/jsduck/Ext.util.Floating.json 
echo Ext.ZIndexManager
./libgen.byte tools/jsduck/Ext.ZIndexManager.json
echo Ext.Component
./libgen.byte tools/jsduck/Ext.Component.json 
echo Ext.util.AbstractMixedCollection
./libgen.byte tools/jsduck/Ext.util.AbstractMixedCollection.json
echo Ext.util.Sorter
./libgen.byte tools/jsduck/Ext.util.Sorter.json
echo Ext.util.Sortable
./libgen.byte tools/jsduck/Ext.util.Sortable.json
echo Ext.util.MixedCollection
./libgen.byte tools/jsduck/Ext.util.MixedCollection.json
echo Ext.layout.ContextItem
./libgen.byte tools/jsduck/Ext.layout.ContextItem.json
echo Ext.layout.Layout
./libgen.byte tools/jsduck/Ext.layout.Layout.json
echo Ext.layout.container.Container
./libgen.byte tools/jsduck/Ext.layout.container.Container.json
echo Ext.container.AbstractContainer
./libgen.byte tools/jsduck/Ext.container.AbstractContainer.json
echo Ext.container.Container
./libgen.byte tools/jsduck/Ext.container.Container.json
echo Ext.container.Viewport
./libgen.byte tools/jsduck/Ext.container.Viewport.json
echo Ext.container.DockingContainer
./libgen.byte tools/jsduck/Ext.container.DockingContainer.json
echo Ext.panel.AbstractPanel
./libgen.byte tools/jsduck/Ext.panel.AbstractPanel.json
echo Ext.panel.Panel
./libgen.byte tools/jsduck/Ext.panel.Panel.json
echo Ext.util.ComponentDragger
./libgen.byte tools/jsduck/Ext.util.ComponentDragger.json
echo Ext.window.Window
./libgen.byte tools/jsduck/Ext.window.Window.json
echo Ext.window.MessageBox
./libgen.byte tools/jsduck/Ext.window.MessageBox.json

