#!/bin/bash

set -e

ocamlbuild tools/libgen.byte
echo Ext.Error
./libgen.byte tools/jsduck/Ext.Error.json 
echo Ext.Class
./libgen.byte tools/jsduck/Ext.Class.json
echo Ext.Base
./libgen.byte tools/jsduck/Ext.Base.json
echo Ext.util.ElementContainer
./libgen.byte tools/jsduck/Ext.util.ElementContainer.json
echo Ext.util.KeyMap
./libgen.byte tools/jsduck/Ext.util.KeyMap.json
echo Ext.util.Observable
./libgen.byte tools/jsduck/Ext.util.Observable.json
echo Ext.util.Offset
./libgen.byte tools/jsduck/Ext.util.Offset.json
echo Ext.util.Region
./libgen.byte tools/jsduck/Ext.util.Region.json
echo Ext.util.Point
./libgen.byte tools/jsduck/Ext.util.Point.json
echo Ext.dd.DragDrop
./libgen.byte tools/jsduck/Ext.dd.DragDrop.json
echo Ext.dd.DD
./libgen.byte tools/jsduck/Ext.dd.DD.json
echo Ext.dd.DDProxy
./libgen.byte tools/jsduck/Ext.dd.DDProxy.json
echo Ext.dd.DDTarget
./libgen.byte tools/jsduck/Ext.dd.DDTarget.json
echo Ext.dd.StatusProxy
./libgen.byte tools/jsduck/Ext.dd.StatusProxy.json
echo Ext.dd.DragSource
./libgen.byte tools/jsduck/Ext.dd.DragSource.json
echo Ext.dd.DragTracker
./libgen.byte tools/jsduck/Ext.dd.DragTracker.json
echo Ext.EventObject
./libgen.byte tools/jsduck/Ext.EventObject.json
echo Ext.dom.AbstractElement
./libgen.byte tools/jsduck/Ext.dom.AbstractElement.json 
echo Ext.dom.Element.Fly
./libgen.byte tools/jsduck/Ext.dom.Element.Fly.json 
echo Ext.ElementLoader
./libgen.byte tools/jsduck/Ext.ElementLoader.json 
echo Ext.dom.Element
./libgen.byte tools/jsduck/Ext.dom.Element.json 
echo Ext.util.Renderable
./libgen.byte tools/jsduck/Ext.util.Renderable.json 
echo Ext.state.Stateful
./libgen.byte tools/jsduck/Ext.state.Stateful.json
echo Ext.util.Animate
./libgen.byte tools/jsduck/Ext.util.Animate.json 
echo Ext.ComponentLoader
./libgen.byte tools/jsduck/Ext.ComponentLoader.json 
echo Ext.AbstractPlugin
./libgen.byte tools/jsduck/Ext.AbstractPlugin.json 
echo Ext.AbstractComponent
./libgen.byte tools/jsduck/Ext.AbstractComponent.json 
echo Ext.util.Floating
./libgen.byte tools/jsduck/Ext.util.Floating.json 
echo Ext.ZIndexManager
./libgen.byte tools/jsduck/Ext.ZIndexManager.json
echo Ext.Component
./libgen.byte tools/jsduck/Ext.Component.json 
echo Ext.util.AbstractMixedCollection
./libgen.byte tools/jsduck/Ext.util.AbstractMixedCollection.json
echo Ext.util.Sorter
./libgen.byte tools/jsduck/Ext.util.Sorter.json
echo Ext.util.Sortable
./libgen.byte tools/jsduck/Ext.util.Sortable.json
echo Ext.util.MixedCollection
./libgen.byte tools/jsduck/Ext.util.MixedCollection.json
echo Ext.layout.ContextItem
./libgen.byte tools/jsduck/Ext.layout.ContextItem.json
echo Ext.layout.Layout
./libgen.byte tools/jsduck/Ext.layout.Layout.json
echo Ext.layout.container.Container
./libgen.byte tools/jsduck/Ext.layout.container.Container.json
echo Ext.container.AbstractContainer
./libgen.byte tools/jsduck/Ext.container.AbstractContainer.json
echo Ext.container.Container
./libgen.byte tools/jsduck/Ext.container.Container.json
echo Ext.container.Viewport
./libgen.byte tools/jsduck/Ext.container.Viewport.json
echo Ext.container.DockingContainer
./libgen.byte tools/jsduck/Ext.container.DockingContainer.json
echo Ext.panel.AbstractPanel
./libgen.byte tools/jsduck/Ext.panel.AbstractPanel.json
echo Ext.panel.Panel
./libgen.byte tools/jsduck/Ext.panel.Panel.json
echo Ext.util.ComponentDragger
./libgen.byte tools/jsduck/Ext.util.ComponentDragger.json
echo Ext.window.Window
./libgen.byte tools/jsduck/Ext.window.Window.json
echo Ext.window.MessageBox
./libgen.byte tools/jsduck/Ext.window.MessageBox.json
echo Ext.data.Errors
./libgen.byte tools/jsduck/Ext.data.Errors.json
echo Ext.data.Field
./libgen.byte tools/jsduck/Ext.data.Field.json
echo Ext.data.Model
./libgen.byte tools/jsduck/Ext.data.Model.json
echo Ext.util.Filter
./libgen.byte tools/jsduck/Ext.util.Filter.json
echo Ext.util.Grouper
./libgen.byte tools/jsduck/Ext.util.Grouper.json
echo Ext.grid.feature.Feature
./libgen.byte tools/jsduck/Ext.grid.feature.Feature.json
echo Ext.data.ResultSet
./libgen.byte tools/jsduck/Ext.data.ResultSet.json
echo Ext.data.Operation
./libgen.byte tools/jsduck/Ext.data.Operation.json
echo Ext.data.reader.Reader
./libgen.byte tools/jsduck/Ext.data.reader.Reader.json
echo Ext.data.Request
./libgen.byte tools/jsduck/Ext.data.Request.json
echo Ext.data.writer.Writer
./libgen.byte tools/jsduck/Ext.data.writer.Writer.json
echo Ext.data.Batch
./libgen.byte tools/jsduck/Ext.data.Batch.json
echo Ext.data.proxy.Proxy
./libgen.byte tools/jsduck/Ext.data.proxy.Proxy.json
echo Ext.data.AbstractStore
./libgen.byte tools/jsduck/Ext.data.AbstractStore.json
echo Ext.data.Store
./libgen.byte tools/jsduck/Ext.data.Store.json
echo Ext.util.Bindable
./libgen.byte tools/jsduck/Ext.util.Bindable.json
echo Ext.selection.Model
./libgen.byte tools/jsduck/Ext.selection.Model.json
echo Ext.selection.DataViewModel
./libgen.byte tools/jsduck/Ext.selection.DataViewModel.json
echo Ext.selection.RowModel
./libgen.byte tools/jsduck/Ext.selection.RowModel.json
echo Ext.view.AbstractView
./libgen.byte tools/jsduck/Ext.view.AbstractView.json
echo Ext.view.View
./libgen.byte tools/jsduck/Ext.view.View.json
echo Ext.view.Table
./libgen.byte tools/jsduck/Ext.view.Table.json
echo Ext.menu.Menu
./libgen.byte tools/jsduck/Ext.menu.Menu.json
echo Ext.grid.plugin.Editing
./libgen.byte tools/jsduck/Ext.grid.plugin.Editing.json
echo Ext.grid.header.Container
./libgen.byte tools/jsduck/Ext.grid.header.Container.json
echo Ext.form.field.Field
./libgen.byte tools/jsduck/Ext.form.field.Field.json
echo Ext.grid.column.Column
./libgen.byte tools/jsduck/Ext.grid.column.Column.json
echo Ext.panel.Table
./libgen.byte tools/jsduck/Ext.panel.Table.json
echo Ext.grid.View
./libgen.byte tools/jsduck/Ext.grid.View.json
echo Ext.grid.Panel
./libgen.byte tools/jsduck/Ext.grid.Panel.json
echo Ext.Template
./libgen.byte tools/jsduck/Ext.Template.json
echo Ext.button.Button
./libgen.byte tools/jsduck/Ext.button.Button.json
echo Ext.data.proxy.Server
./libgen.byte tools/jsduck/Ext.data.proxy.Server.json
echo Ext.data.proxy.Ajax
./libgen.byte tools/jsduck/Ext.data.proxy.Ajax.json
echo Ext.app.Controller
./libgen.byte tools/jsduck/Ext.app.Controller.json
echo Ext.app.Application
./libgen.byte tools/jsduck/Ext.app.Application.json
echo Ext.Version
./libgen.byte tools/jsduck/Ext.Version.json
echo Ext
./libgen.byte tools/jsduck/Ext.json
echo Ext.Loader
./libgen.byte tools/jsduck/Ext.Loader.json
echo Ext.form.action.Action
./libgen.byte tools/jsduck/Ext.form.action.Action.json
echo Ext.form.Basic
./libgen.byte tools/jsduck/Ext.form.Basic.json
echo Ext.form.Labelable
./libgen.byte tools/jsduck/Ext.form.Labelable.json
echo Ext.form.FieldAncestor
./libgen.byte tools/jsduck/Ext.form.FieldAncestor.json
echo Ext.form.Panel
./libgen.byte tools/jsduck/Ext.form.Panel.json
echo Ext.form.field.Base
./libgen.byte tools/jsduck/Ext.form.field.Base.json
echo Ext.form.field.Text
./libgen.byte tools/jsduck/Ext.form.field.Text.json
echo Ext.tip.Tip
./libgen.byte tools/jsduck/Ext.tip.Tip.json
echo Ext.tip.ToolTip
./libgen.byte tools/jsduck/Ext.tip.ToolTip.json
echo Ext.tip.QuickTip
./libgen.byte tools/jsduck/Ext.tip.QuickTip.json
echo Ext.tip.QuickTipManager
./libgen.byte tools/jsduck/Ext.tip.QuickTipManager.json
echo Ext.state.Provider
./libgen.byte tools/jsduck/Ext.state.Provider.json
echo Ext.state.Manager
./libgen.byte tools/jsduck/Ext.state.Manager.json
echo Ext.util.Format
./libgen.byte tools/jsduck/Ext.util.Format.json
echo Ext.MessageBox
./libgen.byte tools/jsduck/Ext.MessageBox.json
echo Ext.Date
./libgen.byte tools/jsduck/Ext.Date.json
echo Ext.chart.Label
./libgen.byte tools/jsduck/Ext.chart.Label.json
echo Ext.chart.axis.Abstract
./libgen.byte tools/jsduck/Ext.chart.axis.Abstract.json
echo Ext.chart.axis.Axis
./libgen.byte tools/jsduck/Ext.chart.axis.Axis.json
echo Ext.chart.series.Series
./libgen.byte tools/jsduck/Ext.chart.series.Series.json
echo Ext.chart.Callout
./libgen.byte tools/jsduck/Ext.chart.Callout.json
echo Ext.chart.Highlight
./libgen.byte tools/jsduck/Ext.chart.Highlight.json
echo Ext.chart.Tip
./libgen.byte tools/jsduck/Ext.chart.Tip.json
echo Ext.draw.Sprite
./libgen.byte tools/jsduck/Ext.draw.Sprite.json
echo Ext.draw.Surface
./libgen.byte tools/jsduck/Ext.draw.Surface.json
echo Ext.LoadMask
./libgen.byte tools/jsduck/Ext.LoadMask.json
echo Ext.draw.Component
./libgen.byte tools/jsduck/Ext.draw.Component.json
echo Ext.chart.Mask
./libgen.byte tools/jsduck/Ext.chart.Mask.json
echo Ext.chart.Navigation
./libgen.byte tools/jsduck/Ext.chart.Navigation.json
echo Ext.chart.theme.Theme
./libgen.byte tools/jsduck/Ext.chart.theme.Theme.json
echo Ext.chart.Chart
./libgen.byte tools/jsduck/Ext.chart.Chart.json
echo Ext.util.Positionable
./libgen.byte tools/jsduck/Ext.util.Positionable.json
echo Ext.enums.Widget
./libgen.byte tools/jsduck/Ext.enums.Widget.json
echo Ext.layout.SizePolicy
./libgen.byte tools/jsduck/Ext.layout.SizePolicy.json

